// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lduqzvfppjsnwyjetqct.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkdXF6dmZwcGpzbnd5amV0cWN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNDU4NDYsImV4cCI6MjA2MjYyMTg0Nn0.AAreaxLFFxDgY8fcM5A4dD6KmIvVRctKKI2u6cWZKUU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);